name: Hello World

on:
   workflow_dispatch:
     

jobs:
    first-job:
        concurrency:
            group: prod
            cancel-in-progress: true
        runs-on: ubuntu-latest
        timeout-minutes: 1
        steps:
          - name: hello world
            run: |
              sleep 300s
              echo "hello world!"
          - name: github
            run: ${{github}}