name: second workdflow

on:
   workflow_dispatch: 

jobs:
    first-job:
        concurrency:
            group: prod
            cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
          - name: hello world
            run: |
              sleep 300s
              echo "hello world!"